name: Docker Image CI

on: 
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**' 

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout

env:
  ACR_NAME: weatheracr123
  IMAGE_NAME: weather-app1988
  RESOURCE_GROUP: weather-rg
  WEBAPP_NAME: weather-app1988
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout clones repo to runner
      uses: actions/checkout@v4

    # setup/install terraform version
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
       terraform_version: 1.5.0
       
     #login to Azure
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

    - name: terraform init
      run: |
        cd terraform
        terraform init -upgrade
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: terraform apply
      run: |
        cd terraform
        terraform apply -auto-approve
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: ACR login
      run: |
        az acr login --name $ACR_NAME
    
    - name: Build the Docker image
      run: |
        docker build --file Dockerfile --tag $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .

    - name: Push image to ACR
      run: |
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
